import "./styles.css";

export default function App() {
  function printTest() {
    window.print();
  }

  return (
    <>
      <div id="not-print" className="App">
        <h1>Hora de imprimir</h1>
        <button onClick={printTest}>Imprimir</button>
      </div>
      <div id="print" className="App">
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
        <h1>Hora de imprimir</h1>
      </div>
    </>
  );
}
